### ISSUE TITLE
Prognose counted as real

### ISSUE THREAD

**Issue by ralfsteck** [BJReplay/ha-solcast-solar#172]
### The problem

Hi, after installation, the daily Prognose is counted as real PV input. See the new, long, dark brown line. It reflects in the energy graph above as a huge 20kWh PV power usage. I expect Solcast to just add the dotted line to the diagram.

### What version of Solcast Integration has the issue?

v4.1.7

### What version of Home Assistant are you using?

Newest

### Logs debug/info/error output

```txt
No log data
```

**Comment by autoSteve** [comment]
https://github.com/BJReplay/ha-solcast-solar/issues/50

**Comment by autoSteve** [comment]
Did you attach an image? I see nothing here.

By my best guess this is not an integration issue, but a set up issue @ralfsteck, which is why I reference #50. Strange forecast as production issue.

It will be configuration.

If you have upgraded from a very old, likely Oziee version, which oddly did not care about this kind of misconfiguration then this could cause even though "I did nothing but upgrade".

**Comment by ralfsteck** [comment]
You are absolutely right, I defined it as Prognose in the PV entry and it works.
Viele Grüße von Unterwegs

*Von: *Steve Saunders ***@***.***>
*An: *BJReplay/ha-solcast-solar ***@***.***>
*Kopie: *ralfsteck ***@***.***>; Mention ***@***.***>
*Datum: *14.09.2024 14:33:04
*Betreff: *Re: [BJReplay/ha-solcast-solar] Prognose counted as real (Issue #172)

**Comment by autoSteve** [comment]
Good to hear.

Freut mich zu hören, dass es funktioniert.
