### ISSUE TITLE
Auto-update option not available during initial configuration

### ISSUE THREAD

**Issue by denisfrench** [BJReplay/ha-solcast-solar#179]
### The problem

I do not have the auto-update option (seen here from the readme; https://github.com/BJReplay/ha-solcast-solar/raw/main/.github/SCREENSHOTS/install.png) available during initial configuration.

![image](https://github.com/user-attachments/assets/d8d02973-ea3c-4652-aa50-39c61a8f8b2a)

### What version of Solcast Integration has the issue?

4.1.7

### What version of Home Assistant are you using?

2024.10.1

### Diagnostics information

[config_entry-solcast_solar-01J9WGKCZD8D33H2SBCQFQS7J1.json](https://github.com/user-attachments/files/17335917/config_entry-solcast_solar-01J9WGKCZD8D33H2SBCQFQS7J1.json)

### Logs debug/info/error output

```txt
There are no errors in the log after restart.
```

### Additional information

I had previous versions of HA Solcast installed, both from this and the original oziee repository.
I have disabled the previous automation to update Solcast, deleted the integration, removed from HACS, and restarted HA.
I added back into HACS, restarted, and reinstalled the integration.
I still do not have the auto-update option available during configuration.
I do not know if it is relevant, but I also do not several other options seen in the readme (https://github.com/BJReplay/ha-solcast-solar/raw/main/.github/SCREENSHOTS/damp.png), as seen below:

![image](https://github.com/user-attachments/assets/2fb75f2e-7f18-45c5-9521-45026035829b)

**Comment by BJReplay** [comment]
Hi @denisfrench, this option is only available in [v4.1.8](https://github.com/BJReplay/ha-solcast-solar/releases/tag/v4.1.8) which is a pre-release.

If you've completely removed the integration from HACS, if you'd previously enabled access to pre-releases or betas, you may have lost it - in which case, have a look [here](https://github.com/BJReplay/ha-solcast-solar/discussions/148) for information on how to re-enable it, if you're keen to get access to v4.1.8 before this feature is released in full in a week or so.

There is a discussion for [v4.1.8](https://github.com/BJReplay/ha-solcast-solar/discussions/176) if you want to read up, but the release does seem reasonably stable, though there is one bug fixed in the current version that we're testing (not yet available as a pre-release - which is why we haven't promoted v4.1.8 to release status yet - it's not that serious, but if you restart HA while a fetch is pending, sometimes it is possible that two forecast updates can occur on restart.

Note that the screenshots in the screenshots directory don't necessarily reflect the current readme - you have to refer to the published version for what is currently supported in the current release.

**Comment by denisfrench** [comment]
No worries; it's been working fine for years, so I'll just re-enable my automation and wait for the update.

I might be confused, but this is what the readme looks like to me right now (with further reference to auto-update down the page):

![image](https://github.com/user-attachments/assets/d5af879d-313f-446c-be8c-e3a2fd0c5705)

I'm on the main branch, showing release 4.1.7 . So it looks like the readme is referring to 4.1.8 features already. I suppose the misalignment will work itself out once 4.1.8 is published in any case.

![image](https://github.com/user-attachments/assets/00bca698-e448-4399-94e0-8a9d7d927285)

Thanks to @BJReplay for taking over maintainance of this repo, @autoSteve for doing a lot of the heavy lifting, and all other contributors (including the ghost of @oziee) 🙂

**Comment by BJReplay** [comment]
> I might be confused, but this is what the readme looks like to me right now (with further reference to auto-update down the page):

Ok, thanks, let us check - maybe an update to the readme escaped early.

If you're looking at a different branch, you should definitely see that.

**Comment by BJReplay** [comment]
Thanks, @denisfrench, you have brought it to our attention that the readme discusses functionality that is currently only available in v4.1.8 pre-release.

I will update the readme to make this clear.

**Comment by BJReplay** [comment]
Thanks, again, @denisfrench, for bringing the discrepancy between documentation and functionality to our attention!

**Comment by autoSteve** [comment]
I will update the v4.1.9 README.md to note features added in that release, @BJReplay. Prior to GA those notes can be removed.

**Comment by autoSteve** [comment]
Thanks for actually reading the readme, @denisfrench! 😂 And thanks for the thanks!

**Comment by BJReplay** [comment]
@denisfrench v4.2.0 is now out in release status with auto-fetch available.
