### ISSUE TITLE
Incorrect "Dayname" attribute when going from DST to Standard Time

### ISSUE THREAD

**Issue by pvprodk** [BJReplay/ha-solcast-solar#207]
**Describe the bug**
The day after switching DST to Standard Time the upcoming sunday (tomorrow) the sensor attributes incorrect daynames. See picture below

**Expected behavior**
Expected Day 3 to be Monday, Day 4 to be Tuesday etc.

**Screenshots**
![image](https://github.com/user-attachments/assets/bfd56009-5348-4cc3-93cc-f60b4c467e0b)

**Solcast Integration Version**
 - Integration Version v4.2.4

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version  130.0.6723.70

**Smartphone (please complete the following information):**
 - Device: Iphone 14+15
 - OS: 18
 - Browser Companion App

**Additional context**

**Comment by gcoan** [comment]
I get the same on mine.  Its now just after midnight British Summer Time (UTC+1) so pv_today says Saturday

pv_Tomorrow says its going to be Sunday

As does the D3 sensor, also going to be Sunday

And D4 says it will be Monday

Key point is that the clocks have not yet changed from DST, its the future projected days are wrong.

I dare say it will sort itself out after DST swaps, but is an amusing wrinkle

**Comment by autoSteve** [comment]
BST ends tomorrow, so let's wait and see. Did either of you notice this happening during the week in the seven day lead up to the switch? I wonder if you were getting two thursays, then two wednesdays, etc. as the transition loomed.

The day name is likely a symptom and that the data for tommorow and day 3 will be identical, with further days ahead shifted.

`dayname` is set using `start_utc.astimezone(self._tz).strftime("%A")`, which is pretty simple.

`start_utc` is set to `self.get_day_start_utc() + timedelta(days=futureday)` being the start of 'today' i.e. midnight local in universal coordinated time, and this reference point is used to build the forecast data too.

`get_day_start_utc()` returns `dt.now(self._tz).replace(hour=0, minute=0, second=0, microsecond=0).astimezone(timezone.utc)`, which is getting the local time now and setting hour/min/sec to zero i.e. midnight local just gone, then converts this to universal coordinated time.

This is bending my mind while I actually laugh out loud. It will have been a bug forever.

One hour of the day disappears going off daylight time. So what??? Is it because BST is only one hour away from UTC? Probably.

I am going to have to simulate this in a Python test using your TZ!

Any clues from others?

**Comment by pvprodk** [comment]
> Did either of you notice this happening during the week in the seven day lead up to the switch? I wonder if you were getting two thursays, then two wednesdays, etc. as the transition loomed.
> 

I have noticed it for some days now, so when the upcoming Sunday was D7 it probably started.

And thank you for the explanation :)

**Comment by autoSteve** [comment]
I have mentally worked this out without a sim.

It is because of the one hour shift from UTC.

What the code needs to do when calculating the start of future days in UTC is to use the time zone that _would be in force as-at that date_... So it is getting things wrong by an entire day.

But the forecast data returned will be correct for the day I think. You can verify this by looking at up-coming days in the Energy dashboard.

Thanks for pointing it out!

This will likely be fixed in v4.2.5.

**Comment by pvprodk** [comment]
> But the forecast data returned will be correct for the day I think. You can verify this by looking at up-coming days in the Energy dashboard.

I can confirm that the forecast data looks correct.

Thanks again 👍

**Comment by BJReplay** [comment]
> `dayname` is set using `start_utc.astimezone(self._tz).strftime("%A")`, which is pretty simple.

This is the problem.  Assuming that _`dayname` is set using `start_utc.astimezone(self._tz).strftime("%A")`_ this is a feature of HA, you're sort of SOL, here.  There's no one good solution.

If you could pick the middle of the day (e.g. midday), you'd be fine, but if dayname is choosing the start of the day, you're out of luck.

When I had to worry about this in another life, and ran into this problem, and had a choice of what time of day (it didn't have to be the beginning of the day), we chose UTC+14:30 as the time - because was always going to fold back to the correct day no matter what time zone or daylight saving zone you were in.  Worked in NZ in summer, and East Coast US in winter.  We didn't have customers in Alaska, nor ever expected any, so were prepared to live that that baked in tech debt).

**Comment by gcoan** [comment]
> I wonder if you were getting two thursays, then two wednesdays, etc. as the transition loomed. 

Just before midnight I could see today was Friday, tomorrow Saturday, D3 and D4 both Sunday

> One hour of the day disappears going off daylight time. So what??? Is it because BST is only one hour away from UTC? Probably.

I'm expecting an extra hour of the day (night) not an hour less, two 1-2AM's as the clocks adjust from BST to UTC

And impressively the Solcast detailed half hourly forecast correctly shows the duplicated 01:00 and 01:30 slots with the different time zones
![image](https://github.com/user-attachments/assets/98f6338e-deed-4bca-ac36-64294d683f1d)

**Comment by BJReplay** [comment]
We saw a similar thing here - we had a warning for a week or so that there was a day with only 46 out of 48 half hours.

**Comment by gcoan** [comment]
> This will likely be fixed in v4.2.5.

It'll take us a whole year to check that it works 😂

**Comment by BJReplay** [comment]
> It'll take us a whole year to check that it works 😂

All these young kids who have never actually set the time on their PCs for testing time zone related stuff.

**Comment by BJReplay** [comment]
> `dayname` is set using `start_utc.astimezone(self._tz).strftime("%A")`, which is pretty simple.

Now that I've squinted at the code:

```
midday_utc = self.get_day_start_utc() + timedelta(days=futureday) + timedelta(hours=12)
 "dayname": midday_utc .astimezone(self._tz).strftime("%A"),
```

**Comment by autoSteve** [comment]
@gcoan are you able to share what Tuesday next week detailedForecast attribute looks like? Does it start at 00:00:00+00:00 or different?

**Comment by autoSteve** [comment]
Here is exactly the logic that is being followed, and I'm pretty sure it's quite wrong.

'Now' here is the early hours of the 26th Oct in the UK. BST. On Monday in the UK midnight UTC will be 00:00:00+00:00 and not what is being calculated. Correct?

The integration thinks it's 11pm on the day prior.

```
from datetime import datetime as dt
from datetime import timedelta, timezone
import pytz

tz = pytz.timezone("Europe/London")

now = dt.now().astimezone(tz)
print('Now:', now.replace(microsecond=0).isoformat())
day_start = now.replace(hour=0, minute=0, second=0, microsecond=0).astimezone(timezone.utc)
print('Day start UTC:', day_start.isoformat())
monday = day_start + timedelta(days=2)
print('Monday day start UTC:', monday.isoformat())

print(f'\nMonday day start converted to {tz}:', monday.astimezone(tz).isoformat())
```

Output:

```
Now: 2024-10-26T02:36:37+01:00
Day start UTC: 2024-10-25T23:00:00+00:00
Monday day start UTC: 2024-10-27T23:00:00+00:00

Monday day start converted to Europe/London: 2024-10-27T23:00:00+00:00
```

**Comment by autoSteve** [comment]
_This_ looks better to me.

The timedelta must be applied to the local midnight, and not the day_start_utc.

```
from datetime import datetime as dt
from datetime import timedelta, timezone
import pytz

tz = pytz.timezone("Europe/London")

def get_day_start_utc(days_ahead):
    now = dt.now().astimezone(tz).replace(microsecond=0)
    nowplus = (now + timedelta(days=days_ahead)).astimezone(tz)
    day_start = nowplus.replace(hour=0, minute=0, second=0, microsecond=0).astimezone(timezone.utc)
    print('Now:', nowplus, 'Day start UTC:', day_start.isoformat())

for d in range(8):
    get_day_start_utc(d)
```

Output:

```
Now: 2024-10-26 03:10:30+01:00 Day start UTC: 2024-10-25T23:00:00+00:00
Now: 2024-10-27 02:10:30+00:00 Day start UTC: 2024-10-27T00:00:00+00:00
Now: 2024-10-28 02:10:30+00:00 Day start UTC: 2024-10-28T00:00:00+00:00
Now: 2024-10-29 02:10:30+00:00 Day start UTC: 2024-10-29T00:00:00+00:00
Now: 2024-10-30 02:10:30+00:00 Day start UTC: 2024-10-30T00:00:00+00:00
Now: 2024-10-31 02:10:30+00:00 Day start UTC: 2024-10-31T00:00:00+00:00
Now: 2024-11-01 02:10:30+00:00 Day start UTC: 2024-11-01T00:00:00+00:00
Now: 2024-11-02 02:10:30+00:00 Day start UTC: 2024-11-02T00:00:00+00:00
```

**Comment by BJReplay** [comment]
> The timedelta must be applied to the local midnight, and not the day_start_utc.
> 
My only comment (and it is nitpicking, but can avoid problems, particularly around British standard vs summer time, given how close it is to UTC), is that if the timedelta is be applied to the local **_midday_** of the given day, and not the midnight (start) of the given day, it will never run into the transition, particularly for time zones that exist on or around UTC.

`nowplus = (now + timedelta(hours=12) + timedelta(days=days_ahead)).astimezone(tz)`

This obviously won't help you find the start of the day, but will help you land smack bang in the middle of the day (from whence it is simple to find) the:
- name
- start
- end
- etc.

**Comment by autoSteve** [comment]
I'll push a commit soon and you can see what I am doing about it. There is more than one issue.

* The day name is wrong.
* The determination of a future date day_start_utc is wrong when transitioning to or from summer time. The day totals will look right, however the forecast hours built for the Energy dashboard will be shifted by an hour for all days after the transition, until the transition occurs which will 'right' things. 
* The intervals included in forecast slices is wrong when transitioning. This is 48 usually, could be 46 when transitioning to summer time, could be 50 when transitioning to standard time. Presently a flat 48 intervals are grabbed, which does not throw anything off because the sun does not shine around midnight. This throws off the forecast interval check, however, and makes my eye twitch.

> but will help you land smack bang in the middle of the day

How? 'Now' could be 10pm...

**Comment by BJReplay** [comment]
> How? 'Now' could be 10pm...

Indeed. 

Sorry, my first suggested edit was more correct

```
midday_utc = self.get_day_start_utc() + timedelta(days=futureday) + timedelta(hours=12)
 "dayname": midday_utc.astimezone(self._tz).strftime("%A"),

```

Anyway, await your commit.  I'm sure you know what you're doing, and a second set of out of focus eyes, that have done this before, will help spot any gotchas.

**Comment by autoSteve** [comment]
Something's still wrong. I set my dev rig to London time and both tomorrow and Monday (day_3) still show as Sunday. day_4 shows Monday

The forecasts interval count validation appears okay.

I better fix this quick or I'm going to be messing with the dev rig clock.

**Comment by autoSteve** [comment]
The intervals test is (mostly) working as expected.

```
{'intervals': 48, 'correct': True}
{'intervals': 50, 'correct': True}
{'intervals': 48, 'correct': True}
{'intervals': 48, 'correct': True}
{'intervals': 48, 'correct': True}
{'intervals': 48, 'correct': True}
{'intervals': 26, 'correct': False}
{'intervals': 0, 'correct': False}
```

**Comment by autoSteve** [comment]
Easy fix @BJReplay.

It's all working now.

**Comment by gcoan** [comment]
> @gcoan are you able to share what Tuesday next week detailedForecast attribute looks like? Does it start at 00:00:00+00:00 or different?

Sorry Steve, I went to bed and only just saw your message.

As suspected, Tuesday's forecast starts at 23:00:

![image](https://github.com/user-attachments/assets/ef483d3a-136b-447c-b915-208e653c5919)

Of course no sun at that time of the night but all the rest of the forecast for the week will be off by an hour.

It looks like you were on the case anyway by setting your HA to London time zone.  Do you need me to test anything ?

**Comment by gcoan** [comment]
The DST clock change causes such chaos.  Great job in fixing it quickly.

Looking at Predbat's forecast it doesn't have any awareness of the DST change, everything is in (current) local time so it trips through 1am, 2am, 3am Sunday with no recognition that there will be duplicated times.   Hey ho.

Solcast more of an issue because the forecasts are all in UTC and everything is converted back to local TZ.

Out of interest, do you have TZ changes in Australia?

The European Council voted to scrap the TZ change in 2018 but its not been enacted yet https://www.consilium.europa.eu/en/policies/seasonal-time-changes/
UK still occasionally talks about change but I don't believe it's on anyone's political agenda

**Comment by autoSteve** [comment]
> Out of interest, do you have TZ changes in Australia?

We do everywhere except Queensland (their farmers think it fades the curtains and confuses the cows) the Northern Territory (who mostly have desert and put on sweaters when it is below 25C), and Western Australia (who think they live in a different country to the rest of us).

> Do you need me to test anything?

I'm not sure that I do. Daylight time ends for you tomorrow, when normal v4.2.4 service will resume. v4.2.5 is awaiting confirmation that setting a hard limit by individual API key works for anyone else but @BJReplay and I. (I'm pretty sure it does. 😉) That and a bit more bake-in testing.

If you're really keen to smell the future then you could shoehorn in the files at https://github.com/autoSteve/ha-solcast-solar/tree/Hard-limit-by-API-key. Almost every file has changed.

**Comment by gcoan** [comment]
Feature request for Churchill Time....

 https://www.bbc.co.uk/news/articles/c0mznrv3jvmo
