### ISSUE TITLE
Integration cannot be installed

### ISSUE THREAD

**Issue by MysteryMen23** [BJReplay/ha-solcast-solar#22]
**Describe the bug** 
After I have installed the new "core_2024.6.1" update, I cannot select the integration to install under "Click + Add Integrations and select Solcast PV Forecast."

**Comment by dalgibbard** [comment]
@MysteryMen23 since the original Integration disappeared off the face of the map (the original maintainer deleted the entire repo), until a new one is added back into HACS, it won't show up. So in the meantime, @BJReplay has forked it for us, and the steps to add it are:

* If you already had it installed, make a note of your API key, and delete the current integration, and remove it from HACS; Restart HA. Optionally, remove "solcast.json" from the Home Assistant config directory.
* Follow the manual installation steps here: https://github.com/BJReplay/ha-solcast-solar?tab=readme-ov-file#manually-in-hacs

Some people are suggesting that removal isn't necessary, but a clean slate is recommended to avoid issues.

**Comment by BJReplay** [comment]
As noted at the very top of the readme, until the integration is re-included in HACS, you must follow the manual in HACS installation instructions.

Closing.
