### ISSUE TITLE
test.py does not work anymore

### ISSUE THREAD

**Issue by Unlik** [BJReplay/ha-solcast-solar#97]
Hello, I am running with version v4.0.31, and because no entities have any value (just a new integration, API key used, all seems to be good but not) I wanted to try using test.py which does not work:

`TypeError: ConnectionOptions.__init__() missing 5 required positional arguments: 'tz', 'dampening', 'customhoursensor', 'key_estimate', and 'hard_limit'
`

**Comment by autoSteve** [comment]
Yeah...

I suspect that script has not worked for a very long time. Those options were introduced a very long time ago, and I'm not sure it is even worth fixing. It probably wants removing because distraction.

To the topic at hand, no entities have values...

What's in your HA log? It is highly likely that the Solcast API could not be reached for some reason.

Try beta v4.0.39 with a 'redownload' by flipping the `Show beta versions` toggle and report back (after re-checking log after installing that). Much has been fixed, and much has been made more resilient.

![image](https://github.com/user-attachments/assets/857f4591-a6f9-42df-8591-d0d96db7355c)
![image](https://github.com/user-attachments/assets/870e66a3-dc00-4ef6-9793-6d47840c47e9)

**Comment by Unlik** [comment]
Yes, thanks... the latest beta works perfectly ;) Cheers!
